### ISSUE TITLE
theme

### ISSUE THREAD

**Issue by dcrystalj** [newhoa/victory-icon-theme#2]
Please specify in readme which theme do you use on xfce.

Thank you

**Comment by newhoa** [comment]
Hey, thanks for your interest in the theme. It's a Gtk theme that I made a long time ago just for personal use. It's unpublished as of now but I'll work on getting it up here on Github in the next month or so. As for now, try Arc, Vortex (light), Greybird, Numix, Flat-Plat (For Gtk3/Unity/Gnome3), or a combination of these themes and their window borders. Greybird is probably the best choice for XFCE with this icon theme. Anyway, sorry for the confusion. I'll try to get it more complete and put it up here on Github. Thanks!
- Darin

**Comment by newhoa** [comment]
I'm gonna go ahead and close this since it's not an Icon theme issue. I'll try to respond again when I end up uploading it. Thanks!
- Darin
