### ISSUE TITLE
Icon not correct for xfce4-pulseaudio-plugin 

### ISSUE THREAD

**Issue by bioboy** [newhoa/victory-icon-theme#3]
I use xfce4-pulseaudio-plugin instead of the indicator plugin and the icons aren't showing correctly. See these images, one with hover other without.

![hover](https://cloud.githubusercontent.com/assets/1797182/19217655/cbaaf8b0-8e23-11e6-9c5f-440b0baefaba.png)
![no-hover](https://cloud.githubusercontent.com/assets/1797182/19217656/cbadba82-8e23-11e6-9a6c-ab671acefcb3.png)

**Comment by newhoa** [comment]
Thank you for the images! I am not getting this and am also using xfce4-pulseaudio-plugin. So the icons look fine when hovering but change when not hovering? Can you let me know your distribution (and version) and what version of the plugin itself you are using? For reference I'm using Ubuntu 16.04 and xfce4-pulseaudio-plugin 0.2.4-1

Also, you may have already tried but sometimes the XFCE panel gets weird for me when switching themes and I have to log out and back in for things to reinitialize. If you haven't already tried that try that.

Thanks.
- Darin

**Comment by bioboy** [comment]
Actually now that I've played around a bit it seems to only happen in Vertex and Vertex Light themes (not Vertex Dark). So maybe its a bug in those themes. I'm using Arc now without problems.

**Comment by newhoa** [comment]
I'm glad you figured it out! Yeah, I checked and the same thing happens to me on Vertex/Vertex Light. I tried checking the code and looking through the image folders but I couldn't find anything that would cause it. Guess you might have to ask them.

Anyway, thanks for troubleshooting that. Sorry for the trouble, hopefully you can get it resolved.
- Darin
