### ISSUE TITLE
Folder icon width

### ISSUE THREAD

**Issue by LiSongMWO** [newhoa/victory-icon-theme#6]
First of, love the flat visual style. The only thing bothering me is the width:height ratio of the folder icons. To me, they look stretched. And I understand this is an artistic decision but hear me out. 

It's these icons I'm talking about:
![image](https://user-images.githubusercontent.com/5306929/27633464-a30fdc68-5bff-11e7-9b93-8b2c59a6cdd4.png)

I'll try my best to explain why I get thrown off my track every time I look at the folder icons. A folder in real life typically contains papers or documents that typically are A4 or similar in size so the  width:height ratio is somewhere around 1:1.4. This is the size that we naturally associate with folders and is also very prevalent in icon themes for this very reason.

My brain identifies the icon as a folder but it doesn't match my (and I presume many others') visual image of a folder due to the width:height ratio being off by too much. This causes a slight cognitive dissonance every time I look at them. 

Looking at the icon there is a gap between the back pane and the front fold (the white area) and a gradient on the front which indicates that the folder is opened. However if you look at a real opened folder then the front pane would be at an angle to the camera and by perspective projection would have a trapezoid shape (like [this](http://icons.iconarchive.com/icons/iconlicious/misc/512/Folder-icon.png)). But the front fold in the icon isn't shaped like that so it too causes a dissonance in my brain. It doesn't look like I would expect an open folder to look. Compare to the drive icons:
![image](https://user-images.githubusercontent.com/5306929/27634193-a70b2450-5c02-11e7-80cf-eb3f3923d293.png)
 that are perspective projected. And archives:
![image](https://user-images.githubusercontent.com/5306929/27634661-669d41b2-5c04-11e7-9913-6116a739e0ca.png)

I propose to render the folder as being a closed folder with the expected width:height ratio. This would remove both the dissonance from having odd dimensions and also the feeling of a strange 3D projection. Or to render it as being perspective projected in addition to a slight reshape of the dimensions.

I would contribute but I can't draw to save my life, I can only tell why something doesn't "look right".

**Comment by newhoa** [comment]
Thanks for the input and explanation.

I actually kind of like the look of the folder icons. They're meant to look more like legal pad file folders, and folders that leave a bit of a gap in the front at the top, like [this](https://i.imgur.com/sBhzoQT.jpg) ([source](https://www.tops-products.com/file-folder-color-1-3-tab-blue-legal-100-bx.html)). The folder icons took a lot of time to work on. I like that they're kind of abstract and different than other folder icons. The more I made them look "normal" the more they just looked like other icon themes and kind of bored me.

I don't have any plans to rework the folder icons any time soon, they just take a lot of time that I won't have in the near future. But I understand what you mean, and I'll keep that in mind for the future. Thanks again.
