### ISSUE TITLE
Lock Icon Appears huge on nemo

### ISSUE THREAD

**Issue by BurhanDanger** [newhoa/victory-icon-theme#9]
nemo 3.4.7
gtk3 3.22.24+80+g6a4be7f56b-1
OS -> Archlinux

**Comment by newhoa** [comment]
Ha, I just fixed this yesterday! It was for the archive app file-roller, didn't  know it affected nemo too. Just now uploaded it. It's the icon "dialog-password.svg" in the folder /status/16. Thanks for the pic and report!
